# this file was programatically generated by scripts/generate-elements.py
# DO NOT EDIT MANUALLY


class Element(object):

    def __init__(self, name: str, symbol: str, number: int, **kwargs) -> None:
        for k, v in kwargs.items():
            setattr(self, k, v)
        self._name = name
        self._symbol = symbol
        self._number = number

    @property
    def name(self) -> str:
        return self._name

    @property
    def symbol(self) -> str:
        return self._symbol

    @property
    def number(self) -> int:
        return self._number


class H(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Hydrogen', 'H', 1, **kwargs)


class He(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Helium', 'He', 2, **kwargs)


class Li(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Lithium', 'Li', 3, **kwargs)


class Be(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Beryllium', 'Be', 4, **kwargs)


class B(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Boron', 'B', 5, **kwargs)


class C(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Carbon', 'C', 6, **kwargs)


class N(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Nitrogen', 'N', 7, **kwargs)


class O(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Oxygen', 'O', 8, **kwargs)


class F(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Fluorine', 'F', 9, **kwargs)


class Ne(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Neon', 'Ne', 10, **kwargs)


class Na(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Sodium', 'Na', 11, **kwargs)


class Mg(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Magnesium', 'Mg', 12, **kwargs)


class Al(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Aluminum', 'Al', 13, **kwargs)


class Si(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Silicon', 'Si', 14, **kwargs)


class P(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Phosphorus', 'P', 15, **kwargs)


class S(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Sulfur', 'S', 16, **kwargs)


class Cl(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Chlorine', 'Cl', 17, **kwargs)


class Ar(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Argon', 'Ar', 18, **kwargs)


class K(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Potassium', 'K', 19, **kwargs)


class Ca(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Calcium', 'Ca', 20, **kwargs)


class Sc(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Scanadium', 'Sc', 21, **kwargs)


class Ti(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Titanium', 'Ti', 22, **kwargs)


class V(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Vanadium', 'V', 23, **kwargs)


class Cr(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Chromium', 'Cr', 24, **kwargs)


class Mn(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Manganese', 'Mn', 25, **kwargs)


class Fe(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Iron', 'Fe', 26, **kwargs)


class Co(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Cobalt', 'Co', 27, **kwargs)


class Ni(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Nickel', 'Ni', 28, **kwargs)


class Cu(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Copper', 'Cu', 29, **kwargs)


class Zn(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Zinc', 'Zn', 30, **kwargs)


class Ga(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Gallium', 'Ga', 31, **kwargs)


class Ge(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Germanium', 'Ge', 32, **kwargs)


class As(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Arsenic', 'As', 33, **kwargs)


class Se(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Selenium', 'Se', 34, **kwargs)


class Br(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Bromine', 'Br', 35, **kwargs)


class Kr(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Krypton', 'Kr', 36, **kwargs)


class Rb(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Rubidium', 'Rb', 37, **kwargs)


class Sr(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Strontium', 'Sr', 38, **kwargs)


class Y(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Yttrium', 'Y', 39, **kwargs)


class Zr(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Zirconium', 'Zr', 40, **kwargs)


class Nb(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Niobium', 'Nb', 41, **kwargs)


class Mo(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Molybdenum', 'Mo', 42, **kwargs)


class Tc(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Technetium', 'Tc', 43, **kwargs)


class Ru(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Ruthenium', 'Ru', 44, **kwargs)


class Rh(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Rhodium', 'Rh', 45, **kwargs)


class Pd(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Palladium', 'Pd', 46, **kwargs)


class Ag(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Silver', 'Ag', 47, **kwargs)


class Cd(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Cadmium', 'Cd', 48, **kwargs)


class In(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Indium', 'In', 49, **kwargs)


class Sn(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Tin', 'Sn', 50, **kwargs)


class Sb(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Antimony', 'Sb', 51, **kwargs)


class Te(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Tellurium', 'Te', 52, **kwargs)


class I(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Iodine', 'I', 53, **kwargs)


class Xe(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Xenon', 'Xe', 54, **kwargs)


class Cs(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Caesium', 'Cs', 55, **kwargs)


class Ba(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Barium', 'Ba', 56, **kwargs)


class La(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Lanthanum', 'La', 57, **kwargs)


class Ce(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Cerium', 'Ce', 58, **kwargs)


class Pr(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Praseodymium', 'Pr', 59, **kwargs)


class Nd(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Neodymium', 'Nd', 60, **kwargs)


class Pm(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Promethium', 'Pm', 61, **kwargs)


class Sm(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Samarium', 'Sm', 62, **kwargs)


class Eu(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Europium', 'Eu', 63, **kwargs)


class Gd(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Gadolinium', 'Gd', 64, **kwargs)


class Tb(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Terbium', 'Tb', 65, **kwargs)


class Dy(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Dysprosium', 'Dy', 66, **kwargs)


class Ho(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Holmium', 'Ho', 67, **kwargs)


class Er(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Erbium', 'Er', 68, **kwargs)


class Tm(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Thulium', 'Tm', 69, **kwargs)


class Yb(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Ytterbium', 'Yb', 70, **kwargs)


class Lu(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Lutetium', 'Lu', 71, **kwargs)


class Hf(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Hafnium', 'Hf', 72, **kwargs)


class Ta(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Tantalum', 'Ta', 73, **kwargs)


class W(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Tungsten', 'W', 74, **kwargs)


class Re(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Rhenium', 'Re', 75, **kwargs)


class Os(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Osmium', 'Os', 76, **kwargs)


class Ir(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Iridium', 'Ir', 77, **kwargs)


class Pt(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Platinum', 'Pt', 78, **kwargs)


class Au(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Gold', 'Au', 79, **kwargs)


class Hg(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Mercury', 'Hg', 80, **kwargs)


class Tl(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Thallium', 'Tl', 81, **kwargs)


class Pb(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Lead', 'Pb', 82, **kwargs)


class Bi(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Bismuth', 'Bi', 83, **kwargs)


class Po(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Polonium', 'Po', 84, **kwargs)


class At(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Astatine', 'At', 85, **kwargs)


class Rn(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Radon', 'Rn', 86, **kwargs)


class Fr(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Francium', 'Fr', 87, **kwargs)


class Ra(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Radium', 'Ra', 88, **kwargs)


class Ac(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Actinium', 'Ac', 89, **kwargs)


class Th(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Thorium', 'Th', 90, **kwargs)


class Pa(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Protactinium', 'Pa', 91, **kwargs)


class U(Element):

    def __init__(self, **kwargs) -> None:
        super().__init__('Uranium', 'U', 92, **kwargs)
